version: "3.0"
services:
  mangix-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mangix-fe
    ports:
      - "8071:8071"
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime
    restart: always
